---
- name: Apply Kubernetes Deployment
  hosts: k8s
  gather_facts: no

  tasks:
    - name: copy deployment to kubernetes master
      copy: 
        src: deployment.yaml
        dest: /home/ubuntu/
      args:
        chdir: /var/lib/jenkins/workspace/Ansible/
        
    - name: Apply Deployment
      command: kubectl apply -f /home/ubuntu/deployment.yaml
